### ISSUE TITLE
The configuration screenshot link is broken

### ISSUE THREAD

**Issue by Hobbamok** [mkj-is/processing-intellij#3]
`Non-Image content-type returned`
is what you get when you click it, and obviously the project doesnt work without that config

**Comment by mkj-is** [comment]
The screenshot is not longer available, I will update the link in README. Meanwhile here it is for reference:

<img width="1071" alt="processing-intellij" src="https://user-images.githubusercontent.com/708312/114612303-461ef100-9ca2-11eb-85dc-37f423686dfe.png">

**Comment by mkj-is** [comment]
Fixed in e7dab72.
